const Types = {
  SAVE_USER_DATA: 'SAVE_USER_DATA',
  CLEAR_USER_DATA: 'CLEAR_USER_DATA',
  REFRESH_PROFILE: 'REFRESH_PROFILE',
  SAVE_CURRENT_LOCATION: 'SAVE_CURRENT_LOCATION',

  UPDATE_AUTH_DATA: 'UPDATE_AUTH_DATA',
  UPDATED_AUTH: 'UPDATED_AUTH',

  UPDATE_CART: 'UPDATE_CART',
  CLEAR_CART: 'CLEAR_CART',

  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_LOCATION: 'SET_LOCATION',

  SET_BADGE: 'SET_BADGE',
  //amount
  SAVE_AMOUNT: 'SAVE_AMOUNT',
  UPDATED_AUTH_X: 'UPDATED_AUTH_X',
}

export default Types
